package learnings

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nfsarch33/helix-dev-tools/internal/lockfile"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// PromoteResults holds outcomes from the full promotion pipeline.
type PromoteResults struct {
	Promoted WorkspaceResult
	L1Digest int
	L2SOP    int
}

// Total returns the total number of promotion actions.
func (r PromoteResults) Total() int {
	return r.Promoted.Entries + r.Promoted.Patterns + r.Promoted.Episodes + r.L1Digest + r.L2SOP
}

// Summary returns a human-readable summary of promotion actions.
func (r PromoteResults) Summary() string {
	var parts []string
	if r.Promoted.Entries > 0 {
		parts = append(parts, fmt.Sprintf("%d entries", r.Promoted.Entries))
	}
	if r.Promoted.Patterns > 0 {
		parts = append(parts, fmt.Sprintf("%d patterns", r.Promoted.Patterns))
	}
	if r.Promoted.Episodes > 0 {
		parts = append(parts, fmt.Sprintf("%d episodes", r.Promoted.Episodes))
	}
	if r.L1Digest > 0 {
		parts = append(parts, fmt.Sprintf("L1 digest (%d patterns)", r.L1Digest))
	}
	if r.L2SOP > 0 {
		parts = append(parts, fmt.Sprintf("L2 SOP (%d patterns)", r.L2SOP))
	}
	return strings.Join(parts, ", ")
}

// GenerateL1Digest creates the Git-backed startup digest from patterns with 3+ applications.
func GenerateL1Digest(learningsDir, pepperDir string, dryRun bool) int {
	patternsFile := filepath.Join(learningsDir, "PATTERNS.md")
	pats, err := ParsePatterns(patternsFile)
	if err != nil || len(pats) == 0 {
		return 0
	}

	qualifying := patternsAboveThreshold(pats, 3)
	if len(qualifying) == 0 {
		return 0
	}
	if dryRun {
		return len(qualifying)
	}

	sortPatternsDeterministic(qualifying)

	var buf strings.Builder
	buf.WriteString("# Learnings Digest (Auto-Generated)\n\n")
	buf.WriteString("High-confidence patterns from the self-improvement system.\n")
	buf.WriteString("Auto-generated by `cursor-tools promote` from `~/Code/global-kb/learnings/PATTERNS.md`.\n")
	buf.WriteString(fmt.Sprintf("Patterns shown: confidence >= 0.0, applications >= 3. Total: %d.\n\n", len(qualifying)))
	buf.WriteString("| ID | Pattern | Confidence | Apps | Category |\n")
	buf.WriteString("|----|---------|------------|------|----------|\n")

	for _, p := range qualifying {
		buf.WriteString(fmt.Sprintf("| %s | %s | %.1f | %s | %s |\n",
			p.ID, p.Description, p.Confidence, p.ApplicationsRaw, p.Category))
	}

	episodesDir := filepath.Join(learningsDir, "episodes")
	if entries, err := os.ReadDir(episodesDir); err == nil {
		var names []string
		for _, e := range entries {
			if strings.HasSuffix(e.Name(), ".md") {
				names = append(names, e.Name())
			}
		}
		sort.Sort(sort.Reverse(sort.StringSlice(names)))
		if len(names) > 0 {
			buf.WriteString(fmt.Sprintf("\n## Recent Episodes (%d total)\n\n", len(names)))
			limit := 10
			if len(names) < limit {
				limit = len(names)
			}
			for _, n := range names[:limit] {
				buf.WriteString(fmt.Sprintf("- `%s`\n", strings.TrimSuffix(n, ".md")))
			}
		}
	}

	digestPath := filepath.Join(pepperDir, "learnings-digest.md")
	_ = lockfile.LockedWrite(lockFilePath(), digestPath, buf.String())
	return len(qualifying)
}

// GenerateL2SOP creates the L2 KB SOP from patterns with 5+ applications.
func GenerateL2SOP(learningsDir, sopDir string, dryRun bool) int {
	patternsFile := filepath.Join(learningsDir, "PATTERNS.md")
	pats, err := ParsePatterns(patternsFile)
	if err != nil || len(pats) == 0 {
		return 0
	}

	qualifying := patternsAboveThreshold(pats, 5)
	if len(qualifying) == 0 {
		return 0
	}
	if dryRun {
		return len(qualifying)
	}

	byCategory := make(map[string][]Pattern)
	for _, p := range qualifying {
		byCategory[p.Category] = append(byCategory[p.Category], p)
	}

	var cats []string
	for c := range byCategory {
		cats = append(cats, c)
	}
	sort.Strings(cats)

	var buf strings.Builder
	buf.WriteString("# Learned Patterns SOP (Auto-Generated)\n\n")
	buf.WriteString("Battle-tested patterns promoted from the self-improvement system.\n")
	buf.WriteString("These patterns have been validated across 5+ real-world applications.\n")
	buf.WriteString(fmt.Sprintf("Auto-generated by `cursor-tools promote`. Total: %d.\n\n", len(qualifying)))

	for _, cat := range cats {
		buf.WriteString(fmt.Sprintf("## %s\n\n", cases.Title(language.English).String(cat)))
		pats := byCategory[cat]
		sortPatternsDeterministic(pats)
		for _, p := range pats {
			buf.WriteString(fmt.Sprintf("- **%s** (%.1f confidence): %s\n", p.ID, p.Confidence, p.Description))
		}
		buf.WriteString("\n")
	}

	sopPath := filepath.Join(sopDir, "learned-patterns.md")
	_ = lockfile.LockedWrite(lockFilePath(), sopPath, buf.String())
	return len(qualifying)
}

func patternsAboveThreshold(pats map[string]Pattern, minApps int) []Pattern {
	var result []Pattern
	for _, p := range pats {
		if p.Applications >= minApps {
			result = append(result, p)
		}
	}
	return result
}

func sortPatternsDeterministic(pats []Pattern) {
	sort.Slice(pats, func(i, j int) bool {
		if pats[i].Applications != pats[j].Applications {
			return pats[i].Applications > pats[j].Applications
		}
		if pats[i].Confidence != pats[j].Confidence {
			return pats[i].Confidence > pats[j].Confidence
		}
		return pats[i].ID < pats[j].ID
	})
}
