// Package sprintgen renders a Markdown sprint scaffold from the
// Universal Story Scaffold template. The shape is fixed by the
// `cursor-config/rules/sprint-scaffold-7-stories.mdc` always-applied
// rule: 5 themed + 2 universal = 7 stories per sprint.
package sprintgen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// universalStoryScaffoldTemplate is the row block emitted for every
// themed story. Fields are placeholder strings the operator fills in
// before sprint kick-off; the structure is fixed so reviewers know
// where every concern lives.
const universalStoryScaffoldTemplate = `### {{.ID}} -- TODO: short headline

- **Type**: {{.Mode}}
- **Owner repo**: TODO (e.g. cursor-tools)
- **Branch**: feat/{{.IDLower}}-TODO-slug
- **Files**: TODO list with line-count estimates
- **R1 OSS evidence**: TODO (mature OSS first; document buy/build/skip per reuse-mature-oss-first.mdc)
- **RED test**: TODO failing test name + path
- **GREEN summary**: TODO one-paragraph description of the GREEN commit
- **Validation**: ` + "`" + `go test -race -count=3` + "`" + ` clean; ` + "`" + `runx sentrux gate --repo <alias>` + "`" + ` no degradation; ` + "`" + `runx shell-leak-scan --repo <alias>` + "`" + ` 0 findings
- **Acceptance**: TODO concrete pass criteria
- **Pause/resume notes**: TODO handoff path under ` + "`" + `reports/research/{{.SprintLower}}-handoff-<date>.md` + "`" + ` if interrupted
- **Calendar deadline**: TODO (per ` + "`" + `post-sprint-commit-merge.mdc` + "`" + ` last GREEN + 1h)
`

const sprintHeaderTemplate = `## {{.Sprint}} ({{.Mode}}) -- {{.Theme}}

Universal Story Scaffold (per ` + "`" + `cursor-config/rules/sprint-scaffold-7-stories.mdc` + "`" + `):
5 themed stories + 2 universal stories (Hygiene KPI + EvoLoop capsule/retro) = 7 total.

> Generated by ` + "`" + `cursor-tools sprint-scaffold --next-sprint {{.Sprint}} --mode {{.ModeLower}}` + "`" + `.
> Fill TODO fields before sprint kick-off; the scaffold itself is read-only.

`

const universalKPIStoryTemplate = `### {{.Sprint}}-6 -- Hygiene KPI (universal)

- **Type**: Universal (always)
- **Owner repo**: global-kb
- **Branch**: docs/{{.SprintLower}}-mvp-close (or paired with -7)
- **Files**:
  - ` + "`" + `reports/research/sprint-{{.SprintLower}}-hygiene-kpi.md` + "`" + ` (new this sprint)
- **R1 OSS evidence**: n/a (KPI is a markdown snapshot)
- **Acceptance**:
  - Shell-leak count (runx shell-leak-scan --all-repos) recorded.
  - Alias drift gate (runx config check-aliases v299) recorded.
  - Sentrux Quality + complex_fn per touched repo recorded (before / after).
  - Hook hit rate from cursor-tools metrics recorded.
  - Resource-probe NDJSON density (lines/hour) recorded.
  - OCI retry attempts (if mem0-oci-retry plist loaded) recorded.
  - Carry-forward register from previous sprint reviewed and updated.
- **Pause/resume notes**: Hygiene KPI is the last story to close; capture state if interrupted in ` + "`" + `reports/research/{{.SprintLower}}-handoff-<date>.md` + "`" + `.
- **Calendar deadline**: T+60 min from last GREEN commit on themed stories.

`

const universalCapsuleStoryTemplate = `### {{.Sprint}}-7 -- EvoLoop capsule + retro + daily-startup entry (universal)

- **Type**: Universal (always)
- **Owner repo**: global-kb
- **Branch**: docs/{{.SprintLower}}-mvp-close (or paired with -6)
- **Files**:
  - ` + "`" + `global-memories/capsules/{{.SprintLower}}-{{.ThemeSlug}}.md` + "`" + ` (rollup of 5 themed + 2 universal stories with evidence cells)
  - ` + "`" + `sprint-retros/{{.SprintLower}}-{{.ThemeSlug}}.md` + "`" + ` (lessons learnt + carry-forward to next sprint)
  - One-line addition to ` + "`" + `global-memories/daily-startup-prompt.md` + "`" + ` under "Current source-of-truth notes"
- **R1 OSS evidence**: n/a (durable knowledge artefacts)
- **Acceptance**:
  - All three files present and dated within 1h of last GREEN (` + "`" + `post-sprint-commit-merge.mdc` + "`" + `).
  - Plan-sync PR ` + "`" + `docs/{{.SprintLower}}-<theme>` + "`" + ` OPEN against ` + "`" + `cursor-global-kb` + "`" + ` main (never auto-merged).
  - Carry-forward register lists every blocker by repo + branch + last GREEN SHA.
- **Pause/resume notes**: Capsule and retro are the durable record; if interrupted, write ` + "`" + `reports/research/{{.SprintLower}}-handoff-<date>.md` + "`" + ` and update the daily-startup-prompt with the handoff path.
- **Calendar deadline**: T+60 min from last GREEN commit on themed stories.
`

// scaffoldData carries the per-sprint values into the templates.
type scaffoldData struct {
	Sprint      string // e.g. "v337"
	SprintLower string // e.g. "v337" (kept lower for symmetry)
	Mode        string // "MVP" or "QA"
	ModeLower   string // "mvp" or "qa"
	Theme       string
	ThemeSlug   string
}

type storyData struct {
	ID          string // "v337-1"
	IDLower     string // "v337-1"
	Mode        string
	Sprint      string
	SprintLower string
}

// Scaffold generates the Markdown sprint scaffold for the given sprint
// id, mode (MVP / QA), and theme. Output is deterministic and
// byte-for-byte stable so the golden fixture test catches drift.
//
// An empty sprintID returns the empty string (legacy contract). An
// empty mode defaults to "MVP" with the same shape.
func Scaffold(sprintID, mode, theme string) string {
	if sprintID == "" {
		return ""
	}
	mode = strings.ToUpper(strings.TrimSpace(mode))
	if mode == "" {
		mode = "MVP"
	}

	data := scaffoldData{
		Sprint:      sprintID,
		SprintLower: strings.ToLower(sprintID),
		Mode:        mode,
		ModeLower:   strings.ToLower(mode),
		Theme:       theme,
		ThemeSlug:   themeSlug(theme),
	}

	var b strings.Builder

	must(template.Must(template.New("h").Parse(sprintHeaderTemplate)).Execute(&b, data))

	for i := 1; i <= 5; i++ {
		sd := storyData{
			ID:          fmt.Sprintf("%s-%d", sprintID, i),
			IDLower:     strings.ToLower(fmt.Sprintf("%s-%d", sprintID, i)),
			Mode:        mode,
			Sprint:      sprintID,
			SprintLower: data.SprintLower,
		}
		must(template.Must(template.New("s").Parse(universalStoryScaffoldTemplate)).Execute(&b, sd))
		b.WriteString("\n")
	}

	must(template.Must(template.New("k").Parse(universalKPIStoryTemplate)).Execute(&b, data))
	must(template.Must(template.New("c").Parse(universalCapsuleStoryTemplate)).Execute(&b, data))

	return b.String()
}

func themeSlug(theme string) string {
	s := strings.ToLower(strings.TrimSpace(theme))
	var out bytes.Buffer
	prevDash := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
			prevDash = false
		case r == '-' && !prevDash:
			out.WriteRune('-')
			prevDash = true
		case (r == ' ' || r == '_' || r == '+') && !prevDash:
			out.WriteRune('-')
			prevDash = true
		}
	}
	return strings.Trim(out.String(), "-")
}

func must(err error) {
	if err != nil {
		panic(err) // templates are constants; can't fail in practice
	}
}
