package cli

import (
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

var commitMsgExit = os.Exit
var commitMsgStderr io.Writer = os.Stderr

var commitMsgCmd = &cobra.Command{
	Use:   "commit-msg [msg-file]",
	Short: "Reject AI attribution and enforce conventional commit format",
	Args:  cobra.ExactArgs(1),
	RunE:  runCommitMsg,
}

var aiPatterns = []string{
	"made by cursor",
	"generated by ai",
	"generated by cursor",
	"co-authored-by:.*cursor",
	"co-authored-by:.*copilot",
	"co-authored-by:.*claude",
	"created by ai",
	"written by ai",
	"ai-generated",
}

var conventionalFormat = regexp.MustCompile(`^[a-z]+(\([a-zA-Z0-9_-]+\))?: .+`)

func runCommitMsg(_ *cobra.Command, args []string) error {
	data, err := os.ReadFile(args[0])
	if err != nil {
		return fmt.Errorf("read commit message: %w", err)
	}
	msg := string(data)
	msgLower := strings.ToLower(msg)

	for _, pattern := range aiPatterns {
		re := regexp.MustCompile("(?i)" + pattern)
		if re.MatchString(msgLower) {
			fmt.Fprintf(commitMsgStderr, "ERROR: commit message contains AI attribution ('%s').\nRemove AI attribution and try again.\n", pattern)
			commitMsgExit(1)
			return nil
		}
	}

	firstLine := strings.SplitN(msg, "\n", 2)[0]

	if strings.HasPrefix(firstLine, "Merge ") || strings.HasPrefix(firstLine, "auto: ") {
		return nil
	}

	if !conventionalFormat.MatchString(firstLine) {
		fmt.Fprintf(commitMsgStderr, "ERROR: commit message must follow conventional format.\n  Expected: type(scope): message  OR  type: message\n  Got:      %s\n", firstLine)
		commitMsgExit(1)
		return nil
	}

	return nil
}
