package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/nfsarch33/cursor-tools/internal/clilog"
	"github.com/nfsarch33/cursor-tools/internal/config"
)

var sessionHandoffForce bool
var sessionHandoffDryRun bool

var sessionHandoffCmd = &cobra.Command{
	Use:   "session-handoff",
	Short: "Write a session handoff document to global-memories",
	Long: `Writes ~/memo/global-memories/session-handoff-<YYYY-MM-DD>.md with
current platform, git state for all tracked repos, and open-items stubs.
Skips if today's file already exists unless --force is given.`,
	RunE: runSessionHandoff,
}

func init() {
	sessionHandoffCmd.Flags().BoolVar(&sessionHandoffForce, "force", false, "Overwrite today's handoff file if it already exists")
	sessionHandoffCmd.Flags().BoolVar(&sessionHandoffDryRun, "dry-run", false, "Show what would be written without creating the file")
}

func runSessionHandoff(_ *cobra.Command, _ []string) error {
	p := config.DefaultPaths()
	out := clilog.NewPrefixed("[session-handoff]")
	return generateSessionHandoff(p, out, sessionHandoffForce, sessionHandoffDryRun)
}

// generateSessionHandoff is the testable core of the command.
func generateSessionHandoff(p config.Paths, out *clilog.Prefixed, force, dryRun bool) error {
	today := time.Now().UTC().Format("2006-01-02")
	outPath := filepath.Join(p.GlobalMemoriesDir(), "session-handoff-"+today+".md")

	if !force {
		if _, err := os.Stat(outPath); err == nil {
			out.Info("handoff for %s already exists (use --force to overwrite): %s", today, outPath)
			return nil
		}
	}

	content := buildHandoffContent(p, today)

	if dryRun {
		out.Info("[dry-run] would write: %s", outPath)
		out.Info("--- preview ---\n%s", content)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil { // #nosec G306 -- personal config file
		return fmt.Errorf("write handoff: %w", err)
	}
	out.Info("written: %s", outPath)
	return nil
}

func buildHandoffContent(p config.Paths, today string) string {
	hostname, _ := os.Hostname()
	platform := p.PlatformProfile()

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Session Handoff: %s\n\n", today))
	sb.WriteString(fmt.Sprintf("**Date**: %s  \n", today))
	sb.WriteString(fmt.Sprintf("**Machine**: %s (%s)  \n", hostname, platform))
	sb.WriteString(fmt.Sprintf("**Generated**: %s UTC\n\n", time.Now().UTC().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	sb.WriteString("## Task Summary\n\n")
	sb.WriteString("<!-- TODO: fill in 1-2 sentences describing what was worked on -->\n\n")

	sb.WriteString("## Current State\n\n")
	sb.WriteString(buildRepoSection(p))

	sb.WriteString("## Decisions Made\n\n")
	sb.WriteString("<!-- TODO: numbered list of key decisions and rationale -->\n\n")

	sb.WriteString("## Open Items\n\n")
	sb.WriteString("<!-- TODO: numbered list of remaining work -->\n\n")

	sb.WriteString("## Resume Instructions\n\n")
	sb.WriteString("1. Run: `git -C ~/Code/global-kb pull --ff-only origin main`\n")
	sb.WriteString(fmt.Sprintf("2. Rebuild toolchain if source changed: `cd ~/Code/global-kb/cursor-config/cursor-tools && go build -o ~/bin/cursor-tools ./cmd/cursor-tools/`\n"))
	sb.WriteString("3. Run: `~/bin/cursor-tools doctor resume && ~/bin/cursor-tools health-check`\n")
	sb.WriteString("<!-- TODO: add project-specific resume steps -->\n\n")

	sb.WriteString("## Context Files\n\n")
	sb.WriteString("<!-- TODO: list files the next session should read first -->\n\n")

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by `cursor-tools session-handoff`.*\n")

	return sb.String()
}

// buildRepoSection collects git state for GlobalKB and repos listed in repos-to-sync.txt.
func buildRepoSection(p config.Paths) string {
	var sb strings.Builder

	repos := []string{p.GlobalKB}
	listFile := filepath.Join(p.ToolsDir(), "repos-to-sync.txt")
	if f, err := os.Open(listFile); err == nil {
		defer f.Close()
		lines := make([]byte, 0, 4096)
		buf := make([]byte, 4096)
		for {
			n, err := f.Read(buf)
			lines = append(lines, buf[:n]...)
			if err != nil {
				break
			}
		}
		for _, line := range strings.Split(string(lines), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			if isDir(line) {
				repos = append(repos, line)
			}
		}
	}

	for _, repo := range repos {
		name := filepath.Base(repo)
		branch := gitOutputStr(repo, "rev-parse", "--abbrev-ref", "HEAD")
		commit := gitOutputStr(repo, "log", "--oneline", "-1")
		status := gitOutputStr(repo, "status", "--short")
		dirty := "clean"
		if strings.TrimSpace(status) != "" {
			lines := strings.Count(strings.TrimSpace(status), "\n") + 1
			dirty = fmt.Sprintf("%d uncommitted file(s)", lines)
		}
		sb.WriteString(fmt.Sprintf("### %s\n\n", name))
		sb.WriteString(fmt.Sprintf("- Branch: `%s`\n", branch))
		sb.WriteString(fmt.Sprintf("- Last commit: `%s`\n", commit))
		sb.WriteString(fmt.Sprintf("- Working tree: %s\n\n", dirty))
	}
	return sb.String()
}

func gitOutputStr(repoPath string, args ...string) string {
	fullArgs := append([]string{"-C", repoPath}, args...)
	out, err := exec.Command("git", fullArgs...).Output()
	if err != nil {
		return "(unavailable)"
	}
	return strings.TrimSpace(string(out))
}
