package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nfsarch33/cursor-tools/internal/clilog"
	"github.com/nfsarch33/cursor-tools/internal/config"
	"github.com/nfsarch33/cursor-tools/internal/coordination"
)

func TestRenderHandoff_WithSignals(t *testing.T) {
	signals := []coordination.Signal{
		{Type: coordination.SignalActiveState, Machine: "wsl", Message: "Working on fuzz targets for selfhealv4"},
		{Type: coordination.SignalDecision, Machine: "wsl", Message: "Revert to base Qwen3.5-27B"},
		{Type: coordination.SignalTaskDispatch, Machine: "wsl", TargetFor: "macbook", Message: "Review feat/v10-fuzz-evolver-integration", Priority: "high"},
		{Type: coordination.SignalCompleted, Machine: "wsl", Message: "Added 12 fuzz targets across 6 packages"},
	}

	result := renderHandoff("DESKTOP-078M990", "wsl", "2026-03-20", "### global-kb\n\n- Branch: `main`\n\n", signals)

	if !strings.Contains(result, "## Task Summary") {
		t.Error("missing '## Task Summary' section")
	}
	if !strings.Contains(result, "Working on fuzz targets for selfhealv4") {
		t.Error("missing active-state signal content")
	}
	if !strings.Contains(result, "## Decisions Made") {
		t.Error("missing '## Decisions Made' section")
	}
	if !strings.Contains(result, "Revert to base Qwen3.5-27B") {
		t.Error("missing decision signal content")
	}
	if !strings.Contains(result, "## Delegated Tasks") {
		t.Error("missing '## Delegated Tasks' section")
	}
	if !strings.Contains(result, "*(for macbook)*") {
		t.Error("missing target annotation")
	}
	if strings.Contains(result, "<!-- TODO: fill in 1-2 sentences") {
		t.Error("TODO stubs should be replaced when signals are present")
	}
	if !strings.Contains(result, "signal list") {
		t.Error("resume instructions should mention signal list")
	}
}

func TestRenderHandoff_WithoutSignals(t *testing.T) {
	result := renderHandoff("DESKTOP-078M990", "wsl", "2026-03-20", "### global-kb\n\n", nil)

	if !strings.Contains(result, "<!-- TODO: fill in 1-2 sentences") {
		t.Error("should fall back to TODO stubs when no signals")
	}
	if !strings.Contains(result, "<!-- TODO: numbered list of key decisions") {
		t.Error("should have decisions TODO stub")
	}
}

func TestRenderHandoff_WithBlockers(t *testing.T) {
	signals := []coordination.Signal{
		{Type: coordination.SignalBlocker, Machine: "wsl", Message: "GPU OOM prevents large model loading"},
	}

	result := renderHandoff("DESKTOP-078M990", "wsl", "2026-03-20", "", signals)

	if !strings.Contains(result, "**Blocker**: GPU OOM prevents large model loading") {
		t.Error("blocker should appear in Open Items section")
	}
	if strings.Contains(result, "<!-- TODO: numbered list of remaining work -->") {
		t.Error("Open Items TODO should be replaced when blockers are present")
	}
}

func TestRenderHandoff_HeaderFields(t *testing.T) {
	result := renderHandoff("myhost", "macos", "2026-03-20", "", nil)

	if !strings.Contains(result, "# Session Handoff: 2026-03-20") {
		t.Error("missing date in heading")
	}
	if !strings.Contains(result, "**Machine**: myhost (macos)") {
		t.Error("missing machine info")
	}
	if !strings.Contains(result, "**Date**: 2026-03-20") {
		t.Error("missing date field")
	}
	if !strings.Contains(result, "*Generated by `cursor-tools session-handoff`.*") {
		t.Error("missing generation footer")
	}
}

func TestHasBlockerSignals(t *testing.T) {
	if hasBlockerSignals(nil) {
		t.Error("nil signals should return false")
	}
	if hasBlockerSignals([]coordination.Signal{{Type: coordination.SignalActiveState}}) {
		t.Error("non-blocker signals should return false")
	}
	if !hasBlockerSignals([]coordination.Signal{{Type: coordination.SignalBlocker}}) {
		t.Error("blocker signal should return true")
	}
}

func TestGenerateSessionHandoff_CreatesFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	p := config.Paths{
		Home:     home,
		GlobalKB: filepath.Join(home, "global-kb"),
		Memo:     home,
	}
	gmDir := p.GlobalMemoriesDir()
	os.MkdirAll(gmDir, 0o755)

	origFetch := fetchHandoffSignals
	fetchHandoffSignals = func(_ config.Paths, _ string) []coordination.Signal { return nil }
	defer func() { fetchHandoffSignals = origFetch }()

	out := clilog.NewPrefixed("[test]")
	err := generateSessionHandoff(p, out, false, false)
	if err != nil {
		t.Fatalf("generateSessionHandoff() error = %v", err)
	}

	entries, _ := os.ReadDir(gmDir)
	found := false
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "session-handoff-") {
			found = true
		}
	}
	if !found {
		t.Error("handoff file not created in global-memories dir")
	}
}

func TestGenerateSessionHandoff_SkipsExisting(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	p := config.Paths{
		Home:     home,
		GlobalKB: filepath.Join(home, "global-kb"),
		Memo:     home,
	}
	gmDir := p.GlobalMemoriesDir()
	os.MkdirAll(gmDir, 0o755)

	origFetch := fetchHandoffSignals
	fetchHandoffSignals = func(_ config.Paths, _ string) []coordination.Signal { return nil }
	defer func() { fetchHandoffSignals = origFetch }()

	out := clilog.NewPrefixed("[test]")
	// First call
	_ = generateSessionHandoff(p, out, false, false)
	// Second call should skip (no error, no new file)
	err := generateSessionHandoff(p, out, false, false)
	if err != nil {
		t.Fatalf("second call error = %v", err)
	}
}

func TestGenerateSessionHandoff_ForceOverwrites(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	p := config.Paths{
		Home:     home,
		GlobalKB: filepath.Join(home, "global-kb"),
		Memo:     home,
	}
	gmDir := p.GlobalMemoriesDir()
	os.MkdirAll(gmDir, 0o755)

	origFetch := fetchHandoffSignals
	fetchHandoffSignals = func(_ config.Paths, _ string) []coordination.Signal {
		return []coordination.Signal{
			{Type: coordination.SignalActiveState, Machine: "wsl", Message: "Updated content"},
		}
	}
	defer func() { fetchHandoffSignals = origFetch }()

	out := clilog.NewPrefixed("[test]")
	_ = generateSessionHandoff(p, out, false, false)
	err := generateSessionHandoff(p, out, true, false)
	if err != nil {
		t.Fatalf("force overwrite error = %v", err)
	}

	entries, _ := os.ReadDir(gmDir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "session-handoff-") {
			data, _ := os.ReadFile(filepath.Join(gmDir, e.Name()))
			if !strings.Contains(string(data), "Updated content") {
				t.Error("force overwrite should contain new signal content")
			}
		}
	}
}
